// Generated by CoffeeScript 1.8.0
var fs = require('fs');
var path = require('path');

var webpack = require('webpack');

var webpackDevPort = 7301;

var uglify = new webpack.optimize.UglifyJsPlugin({
  compress: {
    warnings: false
  }
});

var definePlugin = new webpack.DefinePlugin({
  env:{
    isDevelopment:process.env.NODE_ENV !== 'product'
  }

});

var plugins = [definePlugin];


if(process.env.NODE_ENV === 'product'){
  plugins.push(uglify);
}

module.exports = {
  webpackDevPort: webpackDevPort,
  plugins:plugins,
  externals:{
    'pixi':'PIXI',
    'PIXI':'PIXI'
  },
  resolve: {
    extensions: ['', '.js']
  },
  entry: {
    main:'./public/js/newyear/index.js'
  },
  output: {
    path: path.resolve(__dirname, './public/dist'),
    publicPath: "http://localhost:" + webpackDevPort + "/public/dist",
    filename: 'main.js'
  },
  module: {
    loaders: [
      {
        test: /\.ejs$/,
        loader: 'ejs-loader?variable=data'
      }
    ]
  },
  devtool: 'source-map'
};

//# sourceMappingURL=webpack.config.js.map
